### ISSUE TITLE
Landmarks to blendshapes

### ISSUE THREAD

**Issue by SummerSigh** [rwsarmstrong/strongtrack#21]
Hi! First off, amazing tool! It's really great how well this works! However, I do have a question. How does this software convert landmark positions to blend shapes? I see that there is a calibration function and it works really well, but it would be really awesome to know how that works! 

Summer

**Comment by SummerSigh** [comment]
If you have any references, (papers, or code samples) that I could take a look at, that would be greatly appreciated!

**Comment by xuguozhi** [comment]
> If you have any references, (papers, or code samples) that I could take a look at, that would be greatly appreciated!

sparse codes PCA-like algorithm
